apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-74vd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-74vd@sha256:35ef963fb9957907bdd89aa9760ff2bfce1dc6a57698b83f327adb4542734b3d
        name: my-nodejs
        resources: {}
status: {}
